table Sales
	lineageTag: e5f2de38-34f7-41ec-a786-07cdc040ed88

	column Part_Nbr
		dataType: string
		lineageTag: b0afb0ec-0f7b-4ebd-bd52-22218fde63c0
		summarizeBy: none
		sourceColumn: Part_Nbr

		annotation SummarizationSetBy = Automatic

	column Cust_Nbr
		dataType: string
		lineageTag: d7a30a7d-db43-4777-b0f2-4c2c32febaf4
		summarizeBy: none
		sourceColumn: Cust_Nbr

		annotation SummarizationSetBy = Automatic

	column Cost
		dataType: double
		lineageTag: 647e74d7-9434-44b2-b4bb-e5b78c3f48d7
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 9fda843d-9f13-4056-9e45-ca6049ab6392
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column So_Nbr
		dataType: string
		lineageTag: 529c17ce-b3c7-484e-88ec-4d7d27a230ad
		summarizeBy: none
		sourceColumn: So_Nbr

		annotation SummarizationSetBy = Automatic

	column Inv_So_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 429787ff-52f7-431a-8830-ecc4e6c99797
		summarizeBy: none
		sourceColumn: Inv_So_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Sales_Desc
		dataType: string
		lineageTag: d4c30b95-1615-445a-85c2-ec88afcf6e59
		summarizeBy: none
		sourceColumn: Sales_Desc

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: a89b01d2-8519-4dc0-9961-cef290e6c62c
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column 'Sales Amount'
		dataType: double
		lineageTag: 385c2e49-8692-43d5-a17d-12fb8c1d6d75
		summarizeBy: sum
		sourceColumn: Sales Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Primary_Sales_Rep
		dataType: string
		lineageTag: 594958b9-eddc-4682-8604-bb40ccedeea0
		summarizeBy: none
		sourceColumn: Primary_Sales_Rep

		annotation SummarizationSetBy = Automatic

	column Comm_Amt
		dataType: double
		lineageTag: 2e3ff804-54f7-4794-80ec-7cf61322b9ad
		summarizeBy: sum
		sourceColumn: Comm_Amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Sales = m
		mode: import
		source =
				let
				    Source = Sql.Databases(Server),
				    ReportPBI = Source{[Name="ReportPBI"]}[Data],
				    dbo_vw_Sales_Analysis = ReportPBI{[Schema="dbo",Item="vw_Sales_Analysis"]}[Data],
				    #"Renamed Sales Column to Sales Amount" = Table.RenameColumns(dbo_vw_Sales_Analysis,{{"Sales", "Sales Amount"}}),
				    #"Added Profit" = Table.AddColumn(#"Renamed Sales Column to Sales Amount", "Profit", each [Sales Amount] - [Cost]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Profit",{{"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

